import streamlit as st

st.set_page_config(
    page_title="NutriCompare AI | Professor View",
    page_icon="🎓",
    layout="wide",
)

st.title("🎓 NutriCompare AI — Professor View")
st.subheader("Project Documentation Page")

st.divider()

section = st.sidebar.radio(
    "Project Sections",
    [
        "Overview",
        "System Architecture",
        "Components",
        "Methods & Algorithms",
        "Evaluation",
        "Analytics & Leaderboard",
        "Code Structure",
        "Future Work",
    ],
)

if section == "Overview":
    st.header("Project Overview")

    st.markdown("""
NutriCompare AI is a nutrition-focused multi-LLM application developed to compare answers generated by different language models and evaluate their quality using an automated judging mechanism.

The system receives a nutrition-related question from the user and generates responses using two independent language models: **GPT-4o-mini** and **Llama 3.3 70B**. The generated answers are then evaluated through an **LLM-as-a-Judge** workflow, which scores the responses according to predefined criteria and selects a winner.

The application includes additional components such as input validation, nutrition intent classification, meal tracking, meal memory, calorie extraction, question history analysis, analytics dashboards, and evaluation reports.

The project follows a modular architecture based on use cases and application services. Each component has a specific responsibility, making the system easier to maintain, extend, and evaluate.

The main objective of the project is to provide a framework for generating, comparing, evaluating, and analyzing nutrition-related responses produced by multiple large language models.
""")

elif section == "System Architecture":
    st.header("System Architecture")

    st.markdown("""
NutriCompare AI follows a layered architecture consisting of **presentation**, **application**, **domain**, and **infrastructure** components.

The execution flow begins when a user submits a nutrition-related question through the **Streamlit interface**. The request is first processed by the **InputGuardService**, which verifies that the question belongs to the nutrition domain and does not contain unsafe dieting requests.

The validated input is then passed to the **MealTrackingService**, which extracts structured food information, estimates parsing confidence, and updates meal memory when food-related information is detected.

The processed information is used to enrich the prompt before sending it to two independent language models: **GPT-4o-mini** and **Llama 3.3 70B**. Both models generate nutrition-focused responses for the same user question.

After the responses are generated, the **EvaluationService** performs an **LLM-as-a-Judge** evaluation. The judge model compares the answers using multiple criteria including correctness, safety, clarity, and completeness. The evaluation output is parsed and converted into structured scores and a final winner.

Finally, the results are stored and used by analytics, reporting, and leaderboard components to support model comparison and performance analysis.
""")

    st.subheader("Architecture Flow")

    st.code("""
User Question
      ↓
Streamlit User Interface
      ↓
AskNutritionQuestionUseCase
      ↓
ChatService
      ↓
InputGuardService
      ↓
MealCommandHandler
      ↓
MealTrackingService
      ↓
Prompt Enrichment
      ↓
Model A: GPT-4o-mini
      ↓
Model B: Groq Llama 3.3 70B
      ↓
NutritionAnswer
      ↓
CompareLLMAnswersUseCase
      ↓
EvaluationService
      ↓
LLM-as-a-Judge
      ↓
EvaluationResult
      ↓
Analytics / Reports / Leaderboard
""")

    st.subheader("Explore Architecture Components")

    component = st.selectbox(
        "Select a component to see its role in the system:",
        [
            "Streamlit User Interface",
            "AskNutritionQuestionUseCase",
            "ChatService",
            "InputGuardService",
            "MealCommandHandler",
            "MealTrackingService",
            "Prompt Enrichment",
            "Model A: GPT-4o-mini",
            "Model B: Groq Llama 3.3 70B",
            "CompareLLMAnswersUseCase",
            "EvaluationService",
            "Analytics / Reports / Leaderboard",
        ],
    )

    if component == "Streamlit User Interface":
        st.markdown("""
### Streamlit User Interface

The Streamlit interface is the presentation layer of the project. It receives the user question, displays the answers from both models, shows judge results, and provides access to analytics and reports.

**Related layer:** Presentation layer
""")

    elif component == "AskNutritionQuestionUseCase":
        st.markdown("""
### AskNutritionQuestionUseCase

This use case is the entry point for the chat workflow. It receives a `ChatRequest` and delegates the actual processing to `ChatService`.

**Related file:** `src/nutricompare/application/use_cases/ask_nutrition_question.py`
""")

    elif component == "ChatService":
        st.markdown("""
### ChatService

ChatService is the main orchestration service for the nutrition chat workflow. It validates the input, handles meal-memory commands, processes meal-related text, enriches the prompt, calls both LLM clients, extracts calorie estimates, logs the interaction, and returns a `NutritionAnswer`.

**Related file:** `src/nutricompare/application/services/chat_service.py`
""")

    elif component == "InputGuardService":
        st.markdown("""
### InputGuardService

InputGuardService checks whether the user input is allowed. It blocks out-of-domain questions and unsafe dieting requests using unsafe pattern matching and nutrition intent classification.

**Related file:** `src/nutricompare/application/services/input_guard_service.py`
""")

    elif component == "MealCommandHandler":
        st.markdown("""
### MealCommandHandler

MealCommandHandler detects deterministic meal-memory commands such as `today summary`, `meal history`, and `clear memory`. These commands are handled internally without calling the LLMs.

**Related file:** `src/nutricompare/application/services/meal_command_handler.py`
""")

    elif component == "MealTrackingService":
        st.markdown("""
### MealTrackingService

MealTrackingService coordinates food parsing, confidence scoring, and meal memory updates. If food items are detected in the user input, the meal is stored in memory.

**Related file:** `src/nutricompare/application/services/meal_tracking_service.py`
""")

    elif component == "Prompt Enrichment":
        st.markdown("""
### Prompt Enrichment

Before calling the LLMs, the system enriches the user question with detected intent and parsed food items. This gives both models the same structured context.

**Implemented in:** `ChatService.ask_question`
""")

    elif component == "Model A: GPT-4o-mini":
        st.markdown("""
### Model A: GPT-4o-mini

GPT-4o-mini is the first model used in the comparison workflow. It receives the enriched prompt and generates one nutrition-focused answer.

**Role:** First candidate answer
""")

    elif component == "Model B: Groq Llama 3.3 70B":
        st.markdown("""
### Model B: Groq Llama 3.3 70B

Groq Llama 3.3 70B is the second model used in the comparison workflow. It receives the same enriched prompt and generates an alternative nutrition-focused answer.

**Role:** Second candidate answer
""")

    elif component == "CompareLLMAnswersUseCase":
        st.markdown("""
### CompareLLMAnswersUseCase

This use case is the entry point for the evaluation workflow. It receives an `EvaluationRequest` containing the user question and both model answers, then delegates the comparison to `EvaluationService`.

**Related file:** `src/nutricompare/application/use_cases/compare_llm_answers.py`
""")

    elif component == "EvaluationService":
        st.markdown("""
### EvaluationService

EvaluationService builds the judge prompt, sends the user question and both model answers to the judge LLM, extracts structured scores using regular expressions, determines the winner, and returns an `EvaluationResult`.

The extracted criteria include correctness, safety, clarity, completeness, total score, winner, and explanation.

**Related file:** `src/nutricompare/application/services/evaluation_service.py`
""")

    elif component == "Analytics / Reports / Leaderboard":
        st.markdown("""
### Analytics / Reports / Leaderboard

The evaluation outputs are used to generate reports, analytics, and leaderboard views. These sections help summarize model performance across multiple questions and evaluation runs.

**Related files:** `application/analytics`, `application/reports`, `presentation/streamlit/judge_dashboard.py`
""")

elif section == "Components":
    st.header("Main Components")
    st.info("This section will be completed after the architecture section.")

elif section == "Methods & Algorithms":
    st.header("Methods & Algorithms")
    st.info("This section will describe the methods used in each project component.")

elif section == "Evaluation":
    st.header("Evaluation")
    st.info("This section will describe the evaluation suite and test cases.")

elif section == "Analytics & Leaderboard":
    st.header("Analytics & Leaderboard")
    st.info("This section will describe judge reports, analytics, and leaderboard results.")

elif section == "Code Structure":
    st.header("Code Structure")

    st.code("""
src/nutricompare/
├── domain/
├── application/
├── infrastructure/
├── presentation/
tests/
reports/
professor_app.py
""")

elif section == "Future Work":
    st.header("Future Work")
    st.info("This section will describe possible future improvements.")

st.divider()
st.caption("NutriCompare AI — Professor Documentation View")
