from pydantic import BaseModel, Field


class ModelResponse(BaseModel):
    """
    Represents a response generated by one language model.
    """

    model_name: str = Field(..., description="Name of the LLM")
    provider: str = Field(..., description="Provider of the LLM")
    answer: str = Field(..., description="Generated answer")
